name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Install dependencies
        run: |
          brew install xcbeautify

      - name: Build project
        run: |
          xcodebuild clean build \
            -project ltech.xcodeproj \
            -scheme ltech \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            | xcbeautify

      - name: Run tests
        run: |
          xcodebuild test \
            -project ltech.xcodeproj \
            -scheme ltech \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
            | xcbeautify

