name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Show available schemes (debug info)
        run: xcodebuild -list -project ltech.xcodeproj

      - name: Build and Analyze
        run: |
          xcodebuild clean build analyze \
            -scheme ltech \
            -project ltech.xcodeproj \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            | xcpretty && exit ${PIPESTATUS[0]}

