name: iOS CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build and test
        run: |
          set -o pipefail
          xcodebuild clean build \
            -project ltech.xcodeproj \
            -scheme ltech \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.4' \
            CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcbeautify
